/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.BancoDados;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import modelo.ProfessorM;
import controle.ProfessorC;
/**
 *
 * @author Farezi
 */
public class ProfV extends javax.swing.JInternalFrame {

    DefaultTableModel campos=new DefaultTableModel();
    BancoDados bd = new BancoDados();
    public ResultSet dados;
    /**
     * Creates new form ProfV
     */
    public ProfV() {
        initComponents();
        campos.addColumn("CodDocente");
        campos.addColumn("Nome");
        campos.addColumn("Sobrenome");
        campos.addColumn("Titulacao");
        campos.addColumn("Formacao");
        jtbProf.setModel(campos);
        jtbProf.getColumnModel().getColumn(0).setPreferredWidth(70);
        jtbProf.getColumnModel().getColumn(1).setPreferredWidth(40);
        jtbProf.getColumnModel().getColumn(2).setPreferredWidth(70);
        jtbProf.getColumnModel().getColumn(3).setPreferredWidth(50);
        jtbProf.getColumnModel().getColumn(4).setPreferredWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlCodDocente = new javax.swing.JLabel();
        jlPnome = new javax.swing.JLabel();
        jlSnome = new javax.swing.JLabel();
        jlTitulacao = new javax.swing.JLabel();
        jlFormacao = new javax.swing.JLabel();
        jtCodDocente = new javax.swing.JTextField();
        jtPnome = new javax.swing.JTextField();
        jtSnome = new javax.swing.JTextField();
        jtFormacao = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbBuscaCod = new javax.swing.JButton();
        jcTitulacao = new javax.swing.JComboBox<>();
        jbExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbProf = new javax.swing.JTable();
        jbAtualiza = new javax.swing.JButton();
        jbBuscaTit = new javax.swing.JButton();
        jbBusca = new javax.swing.JToggleButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jlCodDocente.setText("Codigo Docente");

        jlPnome.setText("Primeiro Nome");

        jlSnome.setText("Segundo Nome");

        jlTitulacao.setText("Titulacao");

        jlFormacao.setText("Formacao");

        jtCodDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodDocenteActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProf(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar(evt);
            }
        });

        jbBuscaCod.setText("Busca via Codigo");
        jbBuscaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaProfCod(evt);
            }
        });

        jcTitulacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "M", "D" }));

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove(evt);
            }
        });

        jtbProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbProf);

        jbAtualiza.setText("Atualizar");
        jbAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualiza(evt);
            }
        });

        jbBuscaTit.setText("Busca via Titulacao");
        jbBuscaTit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaProfTit(evt);
            }
        });

        jbBusca.setText("Busca Geral");
        jbBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busca(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbAtualiza)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlCodDocente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtCodDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlPnome)
                                        .addComponent(jlSnome)
                                        .addComponent(jlFormacao)
                                        .addComponent(jlTitulacao))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtSnome, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtPnome, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(114, 114, 114)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbBuscaCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscaTit)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAtualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCodDocente)
                            .addComponent(jtCodDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPnome)
                            .addComponent(jtPnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSnome)
                            .addComponent(jtSnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFormacao)
                            .addComponent(jtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTitulacao)
                            .addComponent(jcTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscaCod)
                    .addComponent(jbBusca)
                    .addComponent(jbBuscaTit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroProf(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProf
        // TODO add your handling code here:
        String sCod=jtCodDocente.getText();
        String sPnome=jtPnome.getText();
        String sSnome=jtSnome.getText();
        char sTitulacao=jcTitulacao.getSelectedItem().toString().charAt(0);
        String sFormacao=jtFormacao.getText();
        int cod=Integer.parseInt(sCod);
        
        ProfessorM pm=new ProfessorM(cod, sPnome, sSnome, sTitulacao, sFormacao);
        ProfessorC pc=new ProfessorC();
        pc.InsereProf(pm);
        
    }//GEN-LAST:event_CadastroProf

    private void limpar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar
        jtCodDocente.setText("");
        jtPnome.setText("");
        jtSnome.setText("");
        jtFormacao.setText("");
        jtCodDocente.setText("");
    }//GEN-LAST:event_limpar

    private void remove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove
       if(jtCodDocente.getText().trim().equals("")){
           System.out.println("Cod nao especificado.");
       }
       else{
           ProfessorC pc=new ProfessorC();
           String sCod=jtCodDocente.getText();
           int cod=Integer.parseInt(sCod);
           pc.RemoveProf(cod);
       }
    }//GEN-LAST:event_remove

    private void atualiza(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualiza
        ProfessorC pc=new ProfessorC();
        char sTitulacao=jcTitulacao.getSelectedItem().toString().charAt(0);
        String sCod=jtCodDocente.getText();
        String snome = jtSnome.getText();
        int cod=Integer.parseInt(sCod);
        pc.Atualiza(cod, sTitulacao,snome);
    }//GEN-LAST:event_atualiza

    private void BuscaProfCod(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaProfCod
        ProfessorC pc=new ProfessorC();
        String sCod=jtCodDocente.getText();
        int cod=Integer.parseInt(sCod);
        try{
                bd.conexao();
                dados=pc.BuscaCodProf(cod);
                int linha = 0;
        while(dados.next()){
                campos.setNumRows(linha+1);
                for (int coluna=1;coluna<=5;coluna++){
                        if(coluna==1){
                                jtbProf.setValueAt(dados.getInt(coluna),linha,coluna-1);
                        } else {
                                jtbProf.setValueAt(dados.getString(coluna),linha,coluna-1);

                        }
                }
                linha++;
        }
        bd.desconecta();
        }catch (Exception erro){
                erro.printStackTrace();
        }
    }//GEN-LAST:event_BuscaProfCod

    private void BuscaProfTit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaProfTit
        ProfessorC pc=new ProfessorC();
        char sTitulacao=jcTitulacao.getSelectedItem().toString().charAt(0);
        try{
                bd.conexao();
                dados=pc.BuscaTitProf(sTitulacao);
                int linha = 0;
        while(dados.next()){
                campos.setNumRows(linha+1);
                for (int coluna=1;coluna<=5;coluna++){
                        if(coluna==1){
                                jtbProf.setValueAt(dados.getInt(coluna),linha,coluna-1);
                        } else {
                                jtbProf.setValueAt(dados.getString(coluna),linha,coluna-1);

                        }
                }
                linha++;
        }
        bd.desconecta();
        }catch (Exception erro){
                erro.printStackTrace();
        }
    }//GEN-LAST:event_BuscaProfTit

    private void Busca(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busca
        ProfessorC pc=new ProfessorC();
        try{
                bd.conexao();
                dados=pc.BuscaProf();
                int linha = 0;
        while(dados.next()){
                campos.setNumRows(linha+1);
                for (int coluna=1;coluna<=5;coluna++){
                        if(coluna==1){
                                jtbProf.setValueAt(dados.getInt(coluna),linha,coluna-1);
                        } else {
                                jtbProf.setValueAt(dados.getString(coluna),linha,coluna-1);

                        }
                }
                linha++;
        }
        bd.desconecta();
        }catch (Exception erro){
                erro.printStackTrace();
        }
    }//GEN-LAST:event_Busca

    private void jtCodDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodDocenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAtualiza;
    private javax.swing.JToggleButton jbBusca;
    private javax.swing.JButton jbBuscaCod;
    private javax.swing.JButton jbBuscaTit;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcTitulacao;
    private javax.swing.JLabel jlCodDocente;
    private javax.swing.JLabel jlFormacao;
    private javax.swing.JLabel jlPnome;
    private javax.swing.JLabel jlSnome;
    private javax.swing.JLabel jlTitulacao;
    private javax.swing.JTextField jtCodDocente;
    private javax.swing.JTextField jtFormacao;
    private javax.swing.JTextField jtPnome;
    private javax.swing.JTextField jtSnome;
    private javax.swing.JTable jtbProf;
    // End of variables declaration//GEN-END:variables
}
